import random
from . import *
from telethon.tl.functions.users import GetFullUserRequest

@HackerSpoilt.on(events.callbackquery.CallbackQuery(data="gen"))
async def gen(event):
    if not (await check_user(event.sender_id)):
        return await event.reply(f"{strt}\n\nOops! You need to join my channel so as to use me!", buttons=[Button.url("Join My Channel", url=ltc)])
    acc = random.choice(listofaccs)
    accn, pasw = acc.split(":")
    xxx = await HackerSpoilt(GetFullUserRequest(event.sender_id))
    botname = (await HackerSpoilt.get_me()).username
    if ACC_NAME is None:
        acnme = ""
    else:
        acnme = ACC_NAME
    await event.edit("""
**Here is your {} account!**

**User** - `{}`
**Password** - `{}`

**Generated by** `{}` **via @{}**""".format(acnme, accn, pasw, xxx.user.first_name, botname),
buttons=[
    [Button.url("Channel", url=ltc), Button.url("Bot", url=f"https://t.me/{botname}")],
    [Button.url("Repo", url="https://github.com/xditya/AccountsGenBot"),
    Button.url("Dev", url="https://t.me/HackerSpoilt")]
])
   await event.edit("""
**Here is your {} account!**

**User** - `{}`
**Password** - `{}`

**Generated by** `{}` **via @{}**""".format(acnme, accn, pasw, xxx.user.first_name, botname),
buttons=[
    [Button.url("Channel", url=ltc), Button.url("Bot", url=f"https://t.me/{botname}")],
    [Button.url("check", url="https://t.me/HackerSpoilt_Network"),
    Button.url("Dev", url="https://t.me/HackerSpoilt")]
])
)]
])
)
